version: "3"

services:
  com.myvirtualcloud.dvx.automation:
    image: andreleibovici/datrium_natural_hazard_protection:latest
    environment:
     # Location (City)
     - prod_location_city=Sunnyvale
     # Country Abbreviation (2-digit)
     - prod_location_country=US
     # DVX Fully-Qualified-Domain-Name
     - prod_dvx_fqdn=
     # DVX Admin username
     - prod_dvx_username=admin
     # DVX Admin Password
     - prod_dvx_password=
     # Choose true or false to enable snapshots replication
     - repl_replicate=false
     # Replication site target as configures in DVX
     - repl_location=
     # Retain snapshot for the specified amount of time (in seconds) from current time.
     # Use 'forever' to retain the snapshot forever.
     - snapshot_retention=3600
     # Filename containing list of vms to protect
     - vms_to_protect_filename=vms_to_protect.txt
     # Frequency to check for natural hazard events (seconds) and snapshot/replicate
     - frequency_check=300
     # Km/h
     - wind_speed_max=40
     # Celsius
     - temperature_max=45
     # Richter scale minimum earthquaque magnitude
     - quake_magnitude_min=4
     # "hour", "day", "week", "month"
     - quake_period=hour
     # You MUST provide a valid public API key from pyowm
     - pyowm_api_key=
     # SMTP server
     - smtp_server=smtp.gmail.com
     # SMTP password
     - smtp_password=
     # SMTP Port
     - smtp_port=587
     # SMTP_sender_email
     - smtp_sender_email=
     # SMTP_receiver_email
     - smtp_receiver_email=
    volumes:
      - /Users/andre/Documents/com.myvirtualcloud.dvx.automation/vms_to_protect.txt:/vms_to_protect.txt
