# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ApiTasks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from IDL.Protos.Extensions import CustomOptions_pb2 as IDL_dot_Protos_dot_Extensions_dot_CustomOptions__pb2
from SysMgmt.Api.IDL.Main import RenderedTask_pb2 as SysMgmt_dot_Api_dot_IDL_dot_Main_dot_RenderedTask__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='ApiTasks.proto',
    package='da.api.tasks',
    syntax='proto2',
    serialized_pb=_b('\n\x0e\x41piTasks.proto\x12\x0c\x64\x61.api.tasks\x1a)IDL/Protos/Extensions/CustomOptions.proto\x1a\'SysMgmt/Api/IDL/Main/RenderedTask.proto\"f\n\nGetRequest\x12;\n\x02id\x18\x01 \x01(\tB+\x92?(*\x02\x18\x01\x32\"Get information about a given taskR\x02id:\x1b\x92?\x18\x42\x16\n\x14Request to get tasks\"f\n\x0bGetResponse\x12\x39\n\x04task\x18\x01 \x03(\x0b\x32\x11.da.api.task.TaskB\x12\x92?\x0f\x32\rList of tasksR\x04task:\x1c\x92?\x19\x42\x17\n\x15Response to get tasks2\xb6\x01\n\x05Tasks\x12\x83\x01\n\x03get\x12\x18.da.api.tasks.GetRequest\x1a\x19.da.api.tasks.GetResponse\"G\x92?D\x12\x16\n\x14\x44\x61\x45xceptionFileNoent\"*\n\x05/{id}\x10\x00\"\x1dGets information about a task(\x00\x1a\'\x92?$\x1a\"\n\t/v1/tasks\x12\x15\x41PIs related to tasksB\x03\x90\x01\x01')
    ,
    dependencies=[IDL_dot_Protos_dot_Extensions_dot_CustomOptions__pb2.DESCRIPTOR,SysMgmt_dot_Api_dot_IDL_dot_Main_dot_RenderedTask__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETREQUEST = _descriptor.Descriptor(
    name='GetRequest',
    full_name='da.api.tasks.GetRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='da.api.tasks.GetRequest.id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?(*\002\030\0012\"Get information about a given task'))),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\222?\030B\026\n\024Request to get tasks')),
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=116,
    serialized_end=218,
)


_GETRESPONSE = _descriptor.Descriptor(
    name='GetResponse',
    full_name='da.api.tasks.GetResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='task', full_name='da.api.tasks.GetResponse.task', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\0172\rList of tasks'))),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\222?\031B\027\n\025Response to get tasks')),
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=220,
    serialized_end=322,
)

_GETRESPONSE.fields_by_name['task'].message_type = SysMgmt_dot_Api_dot_IDL_dot_Main_dot_RenderedTask__pb2._TASK
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['GetResponse'] = _GETRESPONSE

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), dict(
    DESCRIPTOR = _GETREQUEST,
    __module__ = 'ApiTasks_pb2'
    # @@protoc_insertion_point(class_scope:da.api.tasks.GetRequest)
    ))
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), dict(
    DESCRIPTOR = _GETRESPONSE,
    __module__ = 'ApiTasks_pb2'
    # @@protoc_insertion_point(class_scope:da.api.tasks.GetResponse)
    ))
_sym_db.RegisterMessage(GetResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))
_GETREQUEST.fields_by_name['id'].has_options = True
_GETREQUEST.fields_by_name['id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?(*\002\030\0012\"Get information about a given task'))
_GETREQUEST.has_options = True
_GETREQUEST._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\222?\030B\026\n\024Request to get tasks'))
_GETRESPONSE.fields_by_name['task'].has_options = True
_GETRESPONSE.fields_by_name['task']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\0172\rList of tasks'))
_GETRESPONSE.has_options = True
_GETRESPONSE._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\222?\031B\027\n\025Response to get tasks'))

_TASKS = _descriptor.ServiceDescriptor(
    name='Tasks',
    full_name='da.api.tasks.Tasks',
    file=DESCRIPTOR,
    index=0,
    options=_descriptor._ParseOptions(descriptor_pb2.ServiceOptions(), _b('\222?$\032\"\n\t/v1/tasks\022\025APIs related to tasks')),
    serialized_start=325,
    serialized_end=507,
    methods=[
    _descriptor.MethodDescriptor(
        name='get',
        full_name='da.api.tasks.Tasks.get',
        index=0,
        containing_service=None,
        input_type=_GETREQUEST,
        output_type=_GETRESPONSE,
        options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\222?D\022\026\n\024DaExceptionFileNoent\"*\n\005/{id}\020\000\"\035Gets information about a task(\000')),
    ),
])

Tasks = service_reflection.GeneratedServiceType('Tasks', (_service.Service,), dict(
    DESCRIPTOR = _TASKS,
    __module__ = 'ApiTasks_pb2'
    ))

Tasks_Stub = service_reflection.GeneratedServiceStubType('Tasks_Stub', (Tasks,), dict(
    DESCRIPTOR = _TASKS,
    __module__ = 'ApiTasks_pb2'
    ))


# @@protoc_insertion_point(module_scope)
