# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from IDL.Protos.Extensions import CustomOptions_pb2 as IDL_dot_Protos_dot_Extensions_dot_CustomOptions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='Common.proto',
    package='da.api',
    syntax='proto2',
    serialized_pb=_b('\n\x0c\x43ommon.proto\x12\x06\x64\x61.api\x1a)IDL/Protos/Extensions/CustomOptions.proto\"R\n\x0cTaskResponse\x12$\n\x06taskId\x18\x01 \x02(\tB\x0c\x92?\t2\x07Task IDR\x06taskId:\x1c\x92?\x19\x42\x17\n\x15Task for an operation')
    ,
    dependencies=[IDL_dot_Protos_dot_Extensions_dot_CustomOptions__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TASKRESPONSE = _descriptor.Descriptor(
    name='TaskResponse',
    full_name='da.api.TaskResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='taskId', full_name='da.api.TaskResponse.taskId', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\t2\007Task ID'))),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\222?\031B\027\n\025Task for an operation')),
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=67,
    serialized_end=149,
)

DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), dict(
    DESCRIPTOR = _TASKRESPONSE,
    __module__ = 'Common_pb2'
    # @@protoc_insertion_point(class_scope:da.api.TaskResponse)
    ))
_sym_db.RegisterMessage(TaskResponse)


_TASKRESPONSE.fields_by_name['taskId'].has_options = True
_TASKRESPONSE.fields_by_name['taskId']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\t2\007Task ID'))
_TASKRESPONSE.has_options = True
_TASKRESPONSE._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\222?\031B\027\n\025Task for an operation'))
# @@protoc_insertion_point(module_scope)
