# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyValueTypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
    name='KeyValueTypes.proto',
    package='da.core',
    syntax='proto2',
    serialized_pb=_b('\n\x13KeyValueTypes.proto\x12\x07\x64\x61.core\"C\n\x07\x45numVal\x12\x1a\n\x08\x65numType\x18\x01 \x02(\tR\x08\x65numType\x12\x1c\n\tenumValue\x18\x02 \x02(\tR\tenumValue\"M\n\x06MsgVal\x12\x18\n\x07msgType\x18\x01 \x02(\tR\x07msgType\x12)\n\x06keyVal\x18\x02 \x03(\x0b\x32\x11.da.core.KeyValueR\x06keyVal\"\x96\x03\n\nTypedValue\x12,\n\x04type\x18\x01 \x02(\x0e\x32\x18.da.core.TypedValue.TypeR\x04type\x12\x1c\n\tstringVal\x18\x02 \x01(\tR\tstringVal\x12,\n\x11repeatedStringVal\x18\x03 \x03(\tR\x11repeatedStringVal\x12*\n\x07\x65numVal\x18\x04 \x01(\x0b\x32\x10.da.core.EnumValR\x07\x65numVal\x12\x1a\n\x08int64Val\x18\x05 \x01(\x03R\x08int64Val\x12\x1a\n\x08int32Val\x18\x06 \x01(\x05R\x08int32Val\x12\x18\n\x07\x62oolVal\x18\x07 \x01(\x08R\x07\x62oolVal\x12\'\n\x06msgVal\x18\x08 \x01(\x0b\x32\x0f.da.core.MsgValR\x06msgVal\"g\n\x04Type\x12\n\n\x06STRING\x10\x01\x12\x08\n\x04\x45NUM\x10\x02\x12\t\n\x05INT32\x10\x03\x12\t\n\x05INT64\x10\x04\x12\x08\n\x04\x42OOL\x10\x05\x12\x07\n\x03MSG\x10\x06\x12\x13\n\x0fREPEATED_STRING\x10\x14\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x15\"C\n\x08KeyValue\x12\x10\n\x03key\x18\x01 \x02(\tR\x03key\x12%\n\x03val\x18\x02 \x01(\x0b\x32\x13.da.core.TypedValueR\x03val')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TYPEDVALUE_TYPE = _descriptor.EnumDescriptor(
    name='Type',
    full_name='da.core.TypedValue.Type',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='STRING', index=0, number=1,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='ENUM', index=1, number=2,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='INT32', index=2, number=3,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='INT64', index=3, number=4,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='BOOL', index=4, number=5,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='MSG', index=5, number=6,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='REPEATED_STRING', index=6, number=20,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='DEFAULT', index=7, number=21,
            options=None,
            type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=484,
    serialized_end=587,
)
_sym_db.RegisterEnumDescriptor(_TYPEDVALUE_TYPE)


_ENUMVAL = _descriptor.Descriptor(
    name='EnumVal',
    full_name='da.core.EnumVal',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='enumType', full_name='da.core.EnumVal.enumType', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='enumValue', full_name='da.core.EnumVal.enumValue', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=32,
    serialized_end=99,
)


_MSGVAL = _descriptor.Descriptor(
    name='MsgVal',
    full_name='da.core.MsgVal',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='msgType', full_name='da.core.MsgVal.msgType', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='keyVal', full_name='da.core.MsgVal.keyVal', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=101,
    serialized_end=178,
)


_TYPEDVALUE = _descriptor.Descriptor(
    name='TypedValue',
    full_name='da.core.TypedValue',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='type', full_name='da.core.TypedValue.type', index=0,
            number=1, type=14, cpp_type=8, label=2,
            has_default_value=False, default_value=1,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='stringVal', full_name='da.core.TypedValue.stringVal', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='repeatedStringVal', full_name='da.core.TypedValue.repeatedStringVal', index=2,
            number=3, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='enumVal', full_name='da.core.TypedValue.enumVal', index=3,
            number=4, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='int64Val', full_name='da.core.TypedValue.int64Val', index=4,
            number=5, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='int32Val', full_name='da.core.TypedValue.int32Val', index=5,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='boolVal', full_name='da.core.TypedValue.boolVal', index=6,
            number=7, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='msgVal', full_name='da.core.TypedValue.msgVal', index=7,
            number=8, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _TYPEDVALUE_TYPE,
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=181,
    serialized_end=587,
)


_KEYVALUE = _descriptor.Descriptor(
    name='KeyValue',
    full_name='da.core.KeyValue',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='da.core.KeyValue.key', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='val', full_name='da.core.KeyValue.val', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=589,
    serialized_end=656,
)

_MSGVAL.fields_by_name['keyVal'].message_type = _KEYVALUE
_TYPEDVALUE.fields_by_name['type'].enum_type = _TYPEDVALUE_TYPE
_TYPEDVALUE.fields_by_name['enumVal'].message_type = _ENUMVAL
_TYPEDVALUE.fields_by_name['msgVal'].message_type = _MSGVAL
_TYPEDVALUE_TYPE.containing_type = _TYPEDVALUE
_KEYVALUE.fields_by_name['val'].message_type = _TYPEDVALUE
DESCRIPTOR.message_types_by_name['EnumVal'] = _ENUMVAL
DESCRIPTOR.message_types_by_name['MsgVal'] = _MSGVAL
DESCRIPTOR.message_types_by_name['TypedValue'] = _TYPEDVALUE
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE

EnumVal = _reflection.GeneratedProtocolMessageType('EnumVal', (_message.Message,), dict(
    DESCRIPTOR = _ENUMVAL,
    __module__ = 'KeyValueTypes_pb2'
    # @@protoc_insertion_point(class_scope:da.core.EnumVal)
    ))
_sym_db.RegisterMessage(EnumVal)

MsgVal = _reflection.GeneratedProtocolMessageType('MsgVal', (_message.Message,), dict(
    DESCRIPTOR = _MSGVAL,
    __module__ = 'KeyValueTypes_pb2'
    # @@protoc_insertion_point(class_scope:da.core.MsgVal)
    ))
_sym_db.RegisterMessage(MsgVal)

TypedValue = _reflection.GeneratedProtocolMessageType('TypedValue', (_message.Message,), dict(
    DESCRIPTOR = _TYPEDVALUE,
    __module__ = 'KeyValueTypes_pb2'
    # @@protoc_insertion_point(class_scope:da.core.TypedValue)
    ))

class _TypedValue_dot_Type(object):
    STRING = 1
    STRING_STRING = "STRING"
    ENUM = 2
    ENUM_STRING = "ENUM"
    INT32 = 3
    INT32_STRING = "INT32"
    INT64 = 4
    INT64_STRING = "INT64"
    BOOL = 5
    BOOL_STRING = "BOOL"
    MSG = 6
    MSG_STRING = "MSG"
    REPEATED_STRING = 20
    REPEATED_STRING_STRING = "REPEATED_STRING"
    DEFAULT = 21
    DEFAULT_STRING = "DEFAULT"
TypedValue.Type = _TypedValue_dot_Type
_sym_db.RegisterMessage(TypedValue)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
    DESCRIPTOR = _KEYVALUE,
    __module__ = 'KeyValueTypes_pb2'
    # @@protoc_insertion_point(class_scope:da.core.KeyValue)
    ))
_sym_db.RegisterMessage(KeyValue)


# @@protoc_insertion_point(module_scope)
