# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalizableMessageTypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from IDL.Protos.Extensions import CustomOptions_pb2 as IDL_dot_Protos_dot_Extensions_dot_CustomOptions__pb2
from IDL.Protos.Extensions import KeyValueTypes_pb2 as IDL_dot_Protos_dot_Extensions_dot_KeyValueTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='LocalizableMessageTypes.proto',
    package='da.core',
    syntax='proto2',
    serialized_pb=_b('\n\x1dLocalizableMessageTypes.proto\x12\x07\x64\x61.core\x1a)IDL/Protos/Extensions/CustomOptions.proto\x1a)IDL/Protos/Extensions/KeyValueTypes.proto\"c\n\x12LocalizableMessage\x12\x1c\n\tmessageId\x18\x01 \x02(\tR\tmessageId\x12/\n\tkeyValues\x18\x02 \x03(\x0b\x32\x11.da.core.KeyValueR\tkeyValues')
    ,
    dependencies=[IDL_dot_Protos_dot_Extensions_dot_CustomOptions__pb2.DESCRIPTOR,IDL_dot_Protos_dot_Extensions_dot_KeyValueTypes__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOCALIZABLEMESSAGE = _descriptor.Descriptor(
    name='LocalizableMessage',
    full_name='da.core.LocalizableMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='messageId', full_name='da.core.LocalizableMessage.messageId', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='keyValues', full_name='da.core.LocalizableMessage.keyValues', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=128,
    serialized_end=227,
)

_LOCALIZABLEMESSAGE.fields_by_name['keyValues'].message_type = IDL_dot_Protos_dot_Extensions_dot_KeyValueTypes__pb2._KEYVALUE
DESCRIPTOR.message_types_by_name['LocalizableMessage'] = _LOCALIZABLEMESSAGE

LocalizableMessage = _reflection.GeneratedProtocolMessageType('LocalizableMessage', (_message.Message,), dict(
    DESCRIPTOR = _LOCALIZABLEMESSAGE,
    __module__ = 'LocalizableMessageTypes_pb2'
    # @@protoc_insertion_point(class_scope:da.core.LocalizableMessage)
    ))
_sym_db.RegisterMessage(LocalizableMessage)


# @@protoc_insertion_point(module_scope)
